version: '3'

# Run as
# docker-compose build; docker-compose up -d
# Check with
# docker ps
# Then check the logs with
# docker logs --tail 50 $service_name
# docker-compose images
# docker-compose logs --tail 20 $service_name

services:

  mysql_db:
    image: mysql:5.7
    network_mode: bridge
    environment:   # Set up mysql database name and password
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    # networks:
    #   - app-tier

  python_app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql_db
    network_mode: bridge
    # networks:
    #   - app-tier
    ports:
      - "8002:8002"
    # command:
    #   tail -f /dev/null
  streamlit_ui:
    build:
      context: .
      dockerfile: Dockerfile_ui
    depends_on:
      - python_app
    network_mode: bridge
    # networks:
    #   - app-tier
    ports:
      - "8501:8501"
    # command:
    #   tail -f /dev/null

# networks:
#   app-tier:
#     driver: bridge